[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  # This disables the form check via config as well
  NETLIFY_NEXT_VERIFY_FORMS = "false"
  # Optional: helps with stability in subdirectories
  NETLIFY_NEXT_SKEW_PROTECTION = "true"