[build]
  base = "paper-rings-inc"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  # This tells Netlify to use the version we just installed via npm
  package = "@netlify/plugin-nextjs"