[build]
  base = "paper-rings-inc"
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/"
  to = "/paper-rings-inc/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/paper-rings-inc/:splat"
  status = 200